name: Build & Release

on:
  pull_request:
    types:
      - closed
    branches:
      - ci/cd

permissions:
  contents: write

jobs:
  build-windows:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Create tag and release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_VER="$(node -p "require('./package.json').version")"
          git tag "$TAG_VER"
          git push origin "$TAG_VER"
          gh release create "$TAG_VER" \
            --title "VOY! v$TAG_VER"

      - name: Build and publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:win -- --publish always